### ISSUE TITLE
TypeScript SDK: Cannot create webhooks using Bearer authorization (API Key), as it enforces the usage of an access token (`Token token`)

### ISSUE THREAD

**Issue by JCMais** [Carbon-for-Developers/carbon-sdks#25]
To reproduce, create a Client using just an API key and try to fetch the list of webhooks, it will fail with error 422 saying the authorization header is missing, this seems to be due to this line here only taking into account access tokens: https://github.com/Carbon-for-Developers/carbon-sdks/blob/99e092f98d57863b48a180f6bfe09d6490bc9994/typescript/api/webhooks-api-generated.ts#L166-L167

**Comment by dphuang2** [comment]
@JCMais thanks for reporting this. This is because Carbon's API doesn't specify API key authentication for that endpoint. Let me check with the Carbon team to see if this was a mistake.

**Comment by dphuang2** [comment]
@JCMais the latest TypeScript SDK should fix the issue. Thanks!
