### ISSUE TITLE
Overly tight dependency versions

### ISSUE THREAD

**Issue by jbgh2** [Carbon-for-Developers/carbon-sdks#95]
I'm integrating Carbon into a Python SaaS product that uses a wide variety of third party libraries.
I can't install the Python SDK because of version conflicts in urllib3 and cryptography.

urllib3 is the main problem as it is requiring the last v1 version and the requirement spec of ^1.xx.xx doesn't allow for a v2 version.

Can you loosen your dependency requirements?

**Comment by konfig-publisher** [comment]
@jbgh2 Thanks for reporting the issue. To make a change like this we will need to do some compatibility testing to see if the SDK will work with version 2 and if it will break anything.

**Comment by dphuang2** [comment]
We will update the SDKs and notify you once it’s complete.

**Comment by eddiechayes** [comment]
This should be resolved in latest SDK version (https://pypi.org/project/carbon-python-sdk/0.1.33)

**Comment by jbgh2** [comment]
Thank you!
